server:
  port: 8002
spring:
  application:
    name: provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_practice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:cn/hao/**/mapper/*.xml  #将基础entity、mapper单独提一个模块 所以需要查询所有地方的mapper层 包括依赖
  type-aliases-package: cn.hao.*.entity #指定实体类包


eureka:
  client:
    register-with-eureka: true     # 注册到eureka服务
    fetch-registry: true # 定期从服务端获取服务注册并信息以供使用
    service-url:
#      defaultZone: http://localhost:7001/eureka     # 指定了Eureka客户端应该连接到哪个Eureka服务器来获取服务注册表信息
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka     # 指定了Eureka客户端应该连接到哪个Eureka服务器来获取服务注册表信息
  instance:
    instance-id: provider-payment-service8002 #Eureka客户端实例的ID。如果未指定，则使用主机名:端口号的组合作为默认值。