server:
  port: 9007


spring:
  application:
    name: consumer-order-service

  main:
    allow-bean-definition-overriding: true #允许存在多个Feign调用相同Service的接口

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: ${spring.application.name}

#接口请求时间限制设置
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000