server:
  port: 8803

spring:
  application:
    name: stream-mq-consumer-service
  rabbitmq:
    host: 192.168.137.100
    username: root
    password: root
    port: 5672

  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit #消息组件类型
          environment: #环境配置
            spring:
              rabbitmq:
                host: 192.168.137.100
                port: 5672
                username: root
                password: root
      bindings:
        input:
          destination: message-topic
          content-type: application/json
          binder: rabbit
          group: group1


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}${server.port}