server:
  port: 9003

spring:
  application:
    name: consumer-order-service

  cloud:
    consul:
      host: 192.168.137.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat: # 开启心跳功能 consul用来确保服务是否可用
          enabled: true

provider:
  service:
    url: http://provider-payment-service/
