server:
  port: 8005

spring:
  application:
    name: provider-payment-service
  cloud:
    consul:
      host: 192.168.137.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:  # 开启心跳功能 consul用来确保服务是否可用
          enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_practice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:cn/hao/**/mapper/*.xml
  type-aliases-package: cn.hao.*.entity