server:
  port: 5555
spring:
  application:
    name: config-center-service
  profiles:
    include:
      - native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/,classpath:/test-config/,classpath:/config,classpath:/test-config

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}

