server:
  port: 5555
spring:
  application:
    name: config-center-service
  profiles:
    include:
      - native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/,classpath:/test-config/,classpath:/config,classpath:/test-config

  rabbitmq:
    host: 192.168.137.100
    username: root
    password: root


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}


#  对 actuator 监控暴露bus-refresh节点，结合mq，刷新配置中心通知其他服务更新
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


